apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 644932113875.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 644932113875.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 60449c54
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
